### ISSUE TITLE
Is it possible to announce the ban in multiple channels? 

### ISSUE THREAD

**Issue by real-vgi** [Spicord/BanAnnouncer#113]
Hi! I want to announce the ban in 2 different discord channels. 
One for punishment logs in STAFF category and one in the server livechat (discordsrv). 
How can I do that?

**Comment by anvorgesa** [comment]
Hello! Unfortunately that's not possible due to a change made on 29 Oct 2021, the config file remained the same with the option still in plural (channel**s**-to-announce) but internally it was set to only pick the first channel id, that change was made in order to fix a bug (that I don't remember to this date as a lot of time has passed).
