### ISSUE TITLE
Add support for LiteBans ($idRandom)

### ISSUE THREAD

**Issue by TZ122** [Spicord/BanAnnouncer#115]
Litebans has recently added ($idRandom) that generates an ID per punishment. This would be awesome to be able to reference in embeds. (Litebans does not have placeholderapi support)

**Comment by anvorgesa** [comment]
Done https://github.com/Spicord/BanAnnouncer/releases/tag/2.7.3

**Comment by TZ122** [comment]
> Done https://github.com/Spicord/BanAnnouncer/releases/tag/2.7.3

Thanks so much for implementing this! Have I set this up incorrectly? I am receiving the following error: https://pastebin.com/rckHvVnD

Here is my embed: https://pastebin.com/7hm3WL8M

**Comment by anvorgesa** [comment]
Considering I have used the latest LiteBans api version and you are having an error saying that the method does not exist in your plugin, then it is very likely because you are using an outdated litebans version which does not contains the "random id" feature.

And in case you are actually using the latest litebans version, then you will have to report this issue to the creator of litebans for not having that method in the plugin which is currently present in the api.

**Comment by TZ122** [comment]
It seems I was on an outdated build. Works great. Thanks!
