### ISSUE TITLE
BanAnnouncer

### ISSUE THREAD

**Issue by Shucai99** [Spicord/BanAnnouncer#38]
hallo it is possibleto make Notes with advances banms in discord or not?

**Comment by OopsieWoopsie** [comment]
No, you can't make any punishment from BanAnnouncer, this plugin is only intended to *announce* them on Discord.

But due to your bad spelling it seems that english may not be your native language, so maybe you mean to *announce* AdvancedBan notes on Discord? if that's what you meant then you can use this version of BanAnnouncer:
https://github.com/Spicord/BanAnnouncer/releases/tag/2.2.1
before using it you will need to delete your current BanAnnouncer config.yml file so it will generate a new one :)
