### ISSUE TITLE
Litebans MYSQL Sync

### ISSUE THREAD

**Issue by DarkZo0m** [Spicord/BanAnnouncer#50]
Hi , In Another Server when i punishment somebody it does not send in webhook ( Litebans Using )

**Comment by OopsieWoopsie** [comment]
Neither the other LiteBans instances knows when a punishment in another server ocurrs, no matter if they are "synced", in this case "sync" just means "shared storage": all the LiteBans instances shares the same tables for storing punishments, **and that's it**. The other instances do not get notified of anything that happens in another place, and thus it is impossible for BanAnnouncer to know it.

As you are talking about "another server" I assume you are using BungeeCord, if that's the case then just move LiteBans (and BanAnnouncer) to BungeeCord and *remove it* from the Spigot instances. And in case you have in on the individual servers because you want "per-server punishments" then you will need to choose between:
1. Having BanAnnouncer to announce punishments globaly by having it on BungeeCord; or
2. Having "per-server punishments"

Sorry that I can't help much regarding this, but that's all I can do.
