### ISSUE TITLE
Update to 1.18.1

### ISSUE THREAD

**Issue by DeriksonTM** [Spicord/BanAnnouncer#70]
Good day! Happy New Year! ♥ I need your plugin, but on version 1.18.1 I get this message. 

[09:32:36] [Server thread/ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_18_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[09:32:38] [Server thread/WARN]: Legacy plugin BanAnnouncer v2.5.0 does not specify an api-version.

I'm using - 
Purpur 1.18.1
Java 17

**Comment by OopsieWoopsie** [comment]
Hi, is BanAnnouncer **the only plugin** that causes an "Legacy plugin X does not specify an api-version." message?

**Comment by OopsieWoopsie** [comment]
Anyways, it should be fixed on the next release as I made a commit the 29th November adding the api-version value, I just didn't made any release since then as that was the only change since last release and it would not make much sense to make a new release just for it :woman_shrugging: 

I will make a release soon with it but only here on GitHub and not SpigotMC ^^ (because of the lack of enough changes)

**Comment by OopsieWoopsie** [comment]
https://github.com/Spicord/BanAnnouncer/releases/tag/2.5.1

**Comment by DeriksonTM** [comment]
Thank you so much for the quick action, everything works! ♥
